### ISSUE TITLE
채점 서버: cargo_asan 오류

### ISSUE THREAD

**Issue by shapespeare** [kaist-cp/rust-school#2]
안녕하세요. 현재 채점 서버에 사전과제를 제출하는 중 오류가 발생해 글을 올립니다.

test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 43 filtered out; finished in 0.00s

Running with cargo_asan...
Build failed! Error message:
error: "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

혹시 개별적으로 채점 서버에 접속해 해야 할 일이 있나요?

**Comment by jeehoonkang** [comment]
@shapespeare 불편을 겪게 해드려서 죄송합니다. *아마도* toolchain을 설치하다가 timeout에 걸린게 아닌가 하는데, 두세번만 재시도 해보시고 계속 안되면 다시 알려주시겠어요?

영세한 인프라라 죄송합니다-

**Comment by shapespeare** [comment]
금일 세 번 동일한 파일로 시도해본 결과 위에 올린 에러 로그와 같은 상태로 중단되었습니다.

**Comment by jeehoonkang** [comment]
@shapespeare 불편을 드려 죄송합니다. 이제 해결되었을 것으로 생각합니다. (제가 제출했을때 잘 되었습니다.)

**Comment by shapespeare** [comment]
감사합니다. 잘 작동하는 것을 확인했습니다. 다만 HW6에서 제출 기한에 오타가 났는지 2023년까지가 아니라 2013년까지로 되어 있어 제출이 되지 않네요...

**Comment by jeehoonkang** [comment]
@shapespeare 감사합니다! hw6 기한 연장했습니다.

**Comment by jeehoonkang** [comment]
아마 모든 해결되었을 것으로 생각합니다. 혹시 문제가 지속되면 issue 다시 열어주세요.
