### ISSUE TITLE
[KAIST CS220 Assignment 2] 마지막 문제 Test Code 관련 문의

### ISSUE THREAD

**Issue by dongjoocha** [kaist-cp/rust-school#5]
과제 진행 중 궁금한 점이 생겨서 이슈 남깁니다.

KAIST CS220 Assignment 2의 마지막 문제에서 `twelve_days_of_christmas_lyrics()`를 작성해야 하는데요, 가사의 특성상 반복문을 이용하여 해결하면 되는 것으로 이해했습니다. 
그러나 여러 번 시도해도 테스트 코드와 정답이 일치하지 않아 어떤 부분이 다른지 찾아본 결과 **열한 번째 문단**의 다음 부분이 다르다는 것을 확인할 수 있었습니다. (왼쪽이 제 코드, 오른쪽이 테스트 코드의 예시 답안입니다)

<img width="914" alt="image" src="https://user-images.githubusercontent.com/74580163/217474526-346a3eab-3a8c-47b0-8ac5-1b13705c0f4c.png">

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/74580163/217474416-bf49ce70-c454-4808-a6e9-e627e67853bd.png">

Google로 검색한 기존 노래 가사에도 `I sent`로 시작하는 구절은 없는 듯한데 오타가 맞나요?
감사합니다.

**Comment by jeehoonkang** [comment]
이 문제는 반복문을 연습하라는 문제이긴 한데 사실 아주 잘 정의된 문제는 아니긴 합니다... 오타일 것 같긴 한데 걍 상관없이 풀어주시면 될듯합니다~
