### ISSUE TITLE
Homework 1 제출

### ISSUE THREAD

**Issue by baehyunsol** [kaist-cp/rust-school#6]
각 Homework들이 레포지토리의 assignment에 대응되는게 아닌가요? hw1 제출란에 `assignment1.rs`를 제출했는데 채점서버는 zip 파일을 기대하는 것처럼 보입니다.

**Comment by LimitEpsilon** [comment]
안녕하세요, cs431 repo에서는 다음과 같이 제출하라고 되어있는 것 같습니다! [제출](https://github.com/kaist-cp/cs431/blob/main/homework/doc/hello_server.md#submission)

**Comment by jeehoonkang** [comment]
혹시 문제가 지속되면 알려주세요~
